on:
  push:
    branches:
      - master
name: 🚀 Deploy do sistema
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup git auth
        env:
          email: thyybr@gmail.com
          username: thyybrandao
          access_token: "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"
        run: |
          git config --global credential.helper store
          echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $email
          git config --global user.name $username
      - name: deploy to gh-pages
        run: |
          npm i
          NODE_ENV=production npm run build
      - uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ftp.codeslayers.com.br
          ftp_username: u667992605.thyy
          ftp_password: 22041991zX!
          local_source_dir: "dist/"
          dist_target_dir: "/rei/lp/"
          delete: "true"
          exclude: "'^logs/' '^README.md'"  
      
